### ISSUE TITLE
string interpolation.

### ISSUE THREAD

**Issue by LoyceTsuma** [learn-co-curriculum/dsc-variable-assignment-lab#2] opened 2024-02-20 13:01 UTC
Please discuss this.

**Comment by bpurdy-ds** [comment] 2024-02-20 14:19
Hello. Thank you for reaching out. May you offer details on what the issue is? And please include a link to the Canvas page so we know what class you are in. If it is not a GitHub issue per se, but has to do with understanding the material, please contact your instructor. Either way, please let us know, so we know how to proceed with this GitHub issue.

**Comment by bpurdy-ds** [comment] 2024-02-22 14:15
Hello again @LoyceTsuma. Hope all is well. Please let me know if there is anything I can do to help, or if your problem is resolved, then I can close the ticket. Thanks again for flagging an issue.

**Comment by bpurdy-ds** [comment] 2024-02-23 13:58
I'll close the issue, but please reopen with details if there is anything you need.

**Closed as completed by bpurdy-ds** 2024-02-23 13:58 UTC
